[workspace]
# members = ["packages/*", "contracts/*"]
members = [
    "packages/*",
    "contracts/oraiswap_token",
    "contracts/oraiswap_factory",
    "contracts/oraiswap_pair",
]

[profile.release.package.oraiswap]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
