[package]
name = "oraiswap"
version = "2.4.1"
authors = ["Oraichain Labs","Terraform Labs, PTE."]
edition = "2018"
description = "Common oraiswap types"
license = "Apache-2.0"
repository = "https://github.com/oraiswap/oraiswap"
homepage = "https://oraiswap.io"
documentation = "https://docs.oraiswap.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.16.0" }
cosmwasm-storage = { version = "1.1.8" }
cosmwasm-std = { version = "1.1.8" }
thiserror = { version = "1.0.23" }
# using cw20-base contract as library
cw20-base = { version = "0.16.0", features = ["library"] }
cosmwasm-schema = "1.1.8"
schemars = "0.8.3"
protobuf = { version = "3.2.0", features = ["with-bytes"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# this import is for testing library
cw-multi-test = { version = "0.16.0" }



