[package]
name = "oraix-protocol"
version = "0.1.0"
authors = ["Terraform Labs, PTE.","Orai Labs"]
edition = "2018"
description = "Common helpers for oraix-protocol"
license = "Apache-2.0"
repository = "https://github.com/oraix-protocol/oraix-contracts"
homepage = "https://oraix.finance"
documentation = "https://docs.oraix.finance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.5.0" }
cosmwasm-std = { version = "0.13.2", default-features = false, features = ["iterator"] }
cosmwasm-storage = { version = "0.13.2", default-features = false, features = ["iterator"] }
oraiswap = { path = "../oraiswap" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = { version = "=0.9.1" }

[dev-dependencies]
cosmwasm-schema = "0.13.2"

[profile.release]
overflow-checks = true