[package]
name = "oraiswap_oracle_base"
version = "2.2.0"
authors = [
    "Yun Yeo <YunSuk-Yeo@users.noreply.github.com>",
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of Orai Core"
license = "Apache-2.0"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-storage = { version = "0.13.2" }
cosmwasm-std = "0.13.2"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "0.13.2"
